# Generated by Django 2.2.24 on 2023-05-17 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Title of the event')),
                ('slug', models.CharField(blank=True, max_length=50, verbose_name='Slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Date')),
                ('event_type', models.CharField(choices=[('Meetup', 'Meetup'), ('BootCamp', 'BootCamp'), ('OpenTalks', 'OpenTalks'), ('Hackathon', 'Hackathon')], default='Meetup', max_length=256)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
                ('creator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
