# Generated by Django 2.2.24 on 2023-05-17 09:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models
import gallery.validators
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', imagekit.models.fields.ProcessedImageField(default='', upload_to=gallery.models.Photo.get_gallery_path, validators=[gallery.validators.validate_file_size], verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.ManyToManyField(related_name='album', to='gallery.Photo')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
