# Generated by Django 2.2.24 on 2023-05-19 13:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('creationTime', models.DateTimeField(blank=True, null=True)),
                ('lastEditTime', models.DateTimeField(blank=True, null=True)),
                ('isPublic', models.BooleanField(default=True)),
                ('startTimestamp', models.DateField(verbose_name='Start Time')),
                ('endTimestamp', models.DateField(blank=True, null=True, verbose_name='End Time')),
                ('isAllDay', models.BooleanField(default=False)),
                ('details', ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='EventAdmins', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EventCreator', to=settings.AUTH_USER_MODEL)),
                ('lastEditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventLastEditor', to=settings.AUTH_USER_MODEL)),
                ('sharedGroups', models.ManyToManyField(blank=True, to='members.Group')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Participant')),
                ('issue_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.Event')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
