# Generated by Django 2.2.24 on 2023-05-17 09:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Form')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('allowMultiple', models.BooleanField(default=False, verbose_name='Allow Multiple?')),
                ('submissionDeadline', models.DateTimeField(blank=True, null=True, verbose_name='Submission Deadline')),
                ('applicationLimit', models.IntegerField(blank=True, null=True, verbose_name='Application Limit')),
                ('formFields', models.TextField(blank=True, null=True, verbose_name='Form Fields')),
                ('onSubmitAfterMax', models.CharField(blank=True, choices=[('W', 'Waitlist'), ('D', "Don't Accept")], max_length=1, null=True, verbose_name='On Submit after limit?')),
                ('formHash', models.CharField(blank=True, max_length=500, null=True, verbose_name='Security hash for the form')),
                ('rsvpSubject', models.TextField(blank=True, null=True)),
                ('rsvpMessage', ckeditor.fields.RichTextField(max_length=5000, verbose_name='RSVP Email Message')),
                ('enableCheckIn', models.BooleanField(default=False, verbose_name='Enable Check-In')),
                ('sendRSVP', models.BooleanField(default=True, verbose_name='Send RSVP Email?')),
                ('admins', models.ManyToManyField(blank=True, related_name='formAdmins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hash', models.CharField(blank=True, max_length=1000, null=True)),
                ('submissionTime', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('formData', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('W', 'Waitlisted'), ('U', 'Under Review')], default='U', max_length=1)),
                ('rsvp', models.BooleanField(blank=True, null=True)),
                ('checkIn', models.BooleanField(blank=True, null=True)),
                ('checkInTime', models.DateTimeField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('checkedInBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Form')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
