# Generated by Django 2.2.24 on 2023-05-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
