# Generated by Django 2.2.24 on 2023-05-17 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Module')),
                ('SSID', models.CharField(default='amfoss_', max_length=1000, verbose_name='Current WiFi SSID')),
                ('seed', models.IntegerField(default=1000, verbose_name='Current Seed')),
                ('seedRefreshInterval', models.DurationField(verbose_name='Seed Refresh Min')),
                ('lastRefreshTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Seed Refresh Time')),
                ('isPaused', models.BooleanField(default=True, verbose_name='Is Seed Refresh Paused')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('lastSeen', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Seen')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('sessions', models.TextField(blank=True, null=True, verbose_name='Session JSON data')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberAttendance', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
                ('modules', models.ManyToManyField(to='attendance.Module')),
            ],
        ),
    ]
